#!/bin/sh

### BEGIN INIT INFO
# Provides:        web2influxdb
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start web2influxdb for b2-eclmon
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

case "$1" in
  start)
    echo -n "Starting web2influxdb"
    cd /opt/b2-eclmon/server/src
    screen -d -m -S w2db ./web2influxdb.py
    echo "."
    ;;
  stop)
    echo -n "Stopping web2influxdb"
    kill -9 `/bin/pidof python ./web2influxdb.py`
    echo "."
    ;;
  force-reload|restart)
    sh $0 stop
    sh $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/web2influxdb {start|stop|restart|force-reload}"
    exit 1
    ;;
esac
